#!/usr/bin/env python3
"""Generate REW house-curve files for the 120.blue configuration.

Shape "C" from REW-INVERSION.md step 5: a low shelf plus a broad upper-bass
scoop.  The scoop is the part that matters -- the room is upper-bass dominant
by 3.3 dB, and with a cut-only filter (max gain 0 dB, achieved = min(target,
measurement)) the way to more apparent low end is to pull 80-160 Hz down, not
to raise the shelf.  A taller shelf means LESS cutting, which buys loudness
and lumpiness together.

Two variants are written; both keep the same +4 dB shelf:
    house-curve-C2.txt   scoop -2 dB   start here
    house-curve-C3.txt   scoop -3 dB   fuller, deepen by ear

REW format (help/housecurve.html): "pairs of frequency and offset values
separated by spaces, tabs or commas", frequency in Hz and offset in dB, "only
lines which begin with a number are loaded", and "the first and last values in
the file are used for all frequencies below and above the range of the data".
Load with EQ window -> House Curve preferences.

The curve is flat 0 dB above ~250 Hz on purpose: the division in step 7 is
limited to 20-225 Hz, so the filter is unity up there and any shape put above
the band is decoration.  A treble tilt has to be a separate shelving filter.
"""
import numpy as np

REF = 200.0            # the curve is defined relative to this frequency
SHELF_DB = 4.0         # low shelf, dB at 20-40 Hz
SHELF_F = 55.0         # shelf corner
SHELF_W = 0.55         # shelf width, in ln(f)
SCOOP_F = 115.0        # upper-bass scoop centre
SCOOP_W = 0.34         # scoop width, in ln(f)  -- about 1.1 octave FWHM, Q ~ 1.2


def shelf(f, top):
    """Low shelf normalised to 0 dB at REF."""
    s = 0.5 * (1 - np.tanh(np.log(f / SHELF_F) / SHELF_W))
    s0 = 0.5 * (1 - np.tanh(np.log(REF / SHELF_F) / SHELF_W))
    return top * (s - s0) / (1 - s0)


def curve(f, scoop):
    return shelf(f, SHELF_DB) - scoop * np.exp(-0.5 * (np.log(f / SCOOP_F) / SCOOP_W) ** 2)


f = np.logspace(np.log10(10.0), np.log10(20000.0), 265)   # 1/24 octave

for scoop, name in ((2.0, 'house-curve-C2.txt'), (3.0, 'house-curve-C3.txt')):
    g = curve(f, scoop)
    with open(name, 'w') as fh:
        fh.write('# REW house curve -- DRC-185 / 120.blue, B&W Nautilus 801\n'
                 '# Shape C: +%.1f dB low shelf (corner %.0f Hz) with a broad\n'
                 '# -%.1f dB scoop centred %.0f Hz. 0 dB reference at %.0f Hz.\n'
                 '# Generated by housecurve.py. Load: EQ window -> House Curve.\n'
                 % (SHELF_DB, SHELF_F, scoop, SCOOP_F, REF))
        for fi, gi in zip(f, g):
            fh.write('%.3f %.3f\n' % (fi, gi))
    print('wrote %-20s  %d points' % (name, len(f)))

print('\n           ' + ''.join('%8.0f' % x for x in
                                (20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250)))
for scoop, tag in ((2.0, 'C2  -2 dB'), (3.0, 'C3  -3 dB')):
    print('%-10s ' % tag + ''.join('%+8.2f' % curve(np.array([x]), scoop)[0]
          for x in (20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250)))
